version: "3.9"
services:
  mysql:
    image: mysql:5.7.34
    container_name: mysql
    environment:
      - MYSQL_USER=lessin
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=test
    ports:
      - 3306:3306
    volumes:
      - D:/env/mysql/data:/var/lib/mysql
      - D:/env/mysql/log:/var/log/mysql
#      - D:/env/mysql/conf:/etc/mysql
    command: bash -c
      "
      echo server_id=1 >> /etc/mysql/mysql.conf.d/mysqld.cnf
      &&
      echo log-bin=master >> /etc/mysql/mysql.conf.d/mysqld.cnf
      &&
      echo binlog_format=row >> /etc/mysql/mysql.conf.d/mysqld.cnf
      &&
      /entrypoint.sh mysqld
      --defaults-file=/etc/mysql/my.cnf
      --explicit_defaults_for_timestamp
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      "
    networks:
      - maxwell
  adminer:
    image: adminer:4.8.0
    restart: always
    depends_on:
      - mysql
    ports:
      - 8080:8080
    networks:
      - maxwell
  zookeeper:
    image: zookeeper:3.7.0
    container_name: zookeeper
    networks:
      - maxwell
  kafka:
    image: wurstmeister/kafka:2.12-2.3.1
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_CREATE_TOPICS: maxwell,gateway
    networks:
      - maxwell
  kafkamanager:
    image: kafkamanager/kafka-manager:3.0.0.4
    container_name: kafkamanager
    environment:
      ZK_HOSTS: zookeeper:2181
    ports:
      - 9000:9000
    depends_on:
      - kafka
    networks:
      - maxwell
  nexus:
    image: sonatype/nexus3:3.30.1
    container_name: nexus
    ports:
      - 8181:8081
    volumes:
      - D:/env/nexus3/data/:/nexus-data
    networks:
      - maxwell
  maxwell:
    build: .
    image: zendesk/maxwell:1.33.0
    container_name: maxwell
    command:
      - "-c"
      - "sed -i 's/\r//' `grep maxwell -rl /app/bin/`; bin/maxwell-docker"
    #command: [ "-c","sed -i 's/\r//' `grep maxwell -rl /app/bin/`; while true; do echo hello; sleep 2; done" ]
    entrypoint: [ "/bin/bash" ]
    depends_on:
      - mysql
      - kafka
      - nexus
    environment:
      - MYSQL_USER=lessin
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=123456
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MAXWELL_PRODUCER=kafka
      - KAFKA_BROKERS=kafka:9092
    networks:
      - maxwell

networks:
  maxwell:
    driver: "bridge"
    name: "maxwell_network"

# docker restart maxwell
# docker attach maxwell
# docker exec -it  maxwell /bin/bash
# docker rmi zendesk/maxwell:1.33.0
# docker rmi $(docker images -q -f dangling=true)
# /bin/bash -c bin/maxwell-docker
# sed -i "s/\r//" filename
# sed -i "s/^M//" filename
# sed -i 's/\r//' `grep maxwell -rl /app/bin/`
# apt-get update && apt-get install vim -y
# chmod -R 644 /etc/mysql
# chmod 0444 my.cnf
# sudo usermod -d /var/lib/mysql/ mysql
# docker volume prune
# docker-compose scale kafka=3
# docker-compose up --scale kafka=3 -d

# /bin/sh -c mkdir -p /usr/share/maven /usr/share/maven/ref

# curl -fSL -o /tmp/apache-maven.tar.gz https://apache.osuosl.org/maven/maven-3/3.8.1/binaries/apache-maven-3.8.1-bin.tar.gz

# tar -xzf /tmp/apache-maven.tar.gz -C /usr/share/maven --strip-components=1

